---
title: "PPP Outline"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(eval = FALSE)
```

## Outline
- Title Slide
- Overview Slide with main sections
- Bayesian Paradigm
- Need for Bayesian Computation
- Bayesian Computational Methods
  - MCMC
  - Gibbs Sampling
    - Users: BUGS/JAGS/Nimble
  - HMC
    - Users: STAN/Greta
- Implementations:
  - BUGS
  - JAGS
  - Nimble
  - STAN
  - Greta
- Data Preparation comparison
  - Generic data prep for all
  - Nimble constants
- Model Specification
  - BUGS
  - JAGS
  - Nimble
  - STAN
- Greta's unique method
  - Data prep
  - Model running
  - Nodes graph
- Computational Time comparison
  - All models
  - STAN compile time
- Accuracy
  - TVD for Conjugate models with analytical posterior known
  - TVD results
  - Sim results for others
  
  
Total Slides: 
  


## Outline with slide count
- Title Slide - 1
- Overview Slide with main sections - 1
- Bayesian Paradigm - 2-3
- Need for Bayesian Computation - 2-3
- History of Computation - 1
  - MCMC - 1-2
  - Gibbs Sampling - 1-2
    - Users: BUGS/JAGS/Nimble
  - HMC - 2-3
    - Users: STAN/Greta
- Methods overview: - 1
  - BUGS - 1
  - JAGS - 1
  - Nimble - 1
  - STAN - 1
  - Greta - 1
- Data Preparation comparison - 1
  - Generic data prep for all - 1
  - Nimble constants - 1
- Model Specification
  - BUGS - 1
  - JAGS - 1
  - Nimble - 1
  - STAN - 1-2
- Greta's unique method
  - Data prep - 1
  - Model running - 1
  - Nodes graph - 1
- Computational Time comparison - 2-3
  - All models
  - STAN compile time
- Accuracy
  - TVD for Conjugate models with analytical posterior known - 1-2
  - TVD results - 1-2
  - Sim results for others - 1-2
  
  
Total Slides: 
