---
title: "Radford Neal HMC notes"
author: "Evan Miyakawa"
date: "4/7/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- Hamiltonian Monte Carlo uses Hamiltonian Dynamics
  - Visualize the dynamics as a frictionless puck that slides over a surface of varying height
    - The state of the system has three elements: position, momentum, and potential energy
  - The position corresponds to variables of interest
  - The potential energy will be minus the log of the probability density for these variables
  - There is one momentum variable for each position variable
- Using "Hamilton's equations", the movement of the puck is computed. 
- For computational implementation, these equations must be approximated by discretizing time, using some small stepsize.
- To use Hamiltonian dynamics to sample from a distribution using MCMC, we need to translate the density function for the distribution to a potential energy function. The variables of interest are now position variables
- We simulate a markov chain where each iteration resamples the momentum variable associated with each position variable and then does a Metroplis update with the proposal found using Hamiltonian dynamics
  - Two steps for each iteration:
    1. New values for the momentum variables are randomly drawn from their Gaussian distribution, independent of the current values of the position variables.
    2. A metropolis update is performed, using hamiltonian dynamics to propose a new state. The proposed state is either accepted or rejected based on the HMC probability function used. If the proposed state is rejected, the next state is the same as the current one.
- The HMC algorithm typically will not be trapped in some subset of the state space, which allows for it to always asymptotically converge to the target distribution, and quickly.
- Tuning Parameters for HMC:
  - Stepsize - the leapfrog stepsize. Too large, and it will lead to a low acceptance rate for proposed states. Too small and it will be slow computationally.
  - Trajectory length - 
