---
title: "Simulation Results"
author: "Evan Miyakawa"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE)
library(tidyverse); options(tibble.width = Inf)
library(magrittr)
theme_set(theme_minimal())
library(here)
```


```{r, eval = FALSE}
exp_gamma_bench_files <- c(
  here("Simulation Results", "simple-models", "continuous", "exponential", "gamma-prior", "exponential-gamma-results.rds"),
  here("Simulation Results", "simple-models", "continuous", "exponential", "gamma-prior", "exponential-gamma-results-greta.rds"),
  here("Simulation Results", "simple-models", "continuous", "exponential", "gamma-prior", "exponential-gamma-results-stan.rds")
)

normal_gamma_tau_bench_files <- c(
  here("Simulation Results", "simple-models", "continuous", "normal", "gamma-prior-tau", "normal-gamma-tau-results.rds"),
  here("Simulation Results", "simple-models", "continuous", "normal", "gamma-prior-tau", "normal-gamma-tau-results-greta.rds"),
  here("Simulation Results", "simple-models", "continuous", "normal", "gamma-prior-tau", "normal-gamma-tau-results-stan.rds")
)

normal_normal_bench_files <- c(
  here("Simulation Results", "simple-models", "continuous", "normal", "normal-prior", "normal-normal-results.rds"),
  here("Simulation Results", "simple-models", "continuous", "normal", "normal-prior", "normal-normal-results-greta.rds"),
  here("Simulation Results", "simple-models", "continuous", "normal", "normal-prior", "normal-normal-results-stan.rds")
)

beta_bernoulli_bench_files <- c(
  here("Simulation Results", "simple-models", "discrete", "bernoulli", "beta-prior", "beta-bernoulli-results.rds"),
  here("Simulation Results", "simple-models", "discrete", "bernoulli", "beta-prior", "beta-bernoulli-results-greta.rds"),
  here("Simulation Results", "simple-models", "discrete", "bernoulli", "beta-prior", "beta-bernoulli-results-stan.rds")
)

beta_binomial_bench_files <- c(
  here("Simulation Results", "simple-models", "discrete", "binomial", "beta-prior", "beta-binomial-results.rds"),
  here("Simulation Results", "simple-models", "discrete", "binomial", "beta-prior", "beta-binomial-results-greta.rds"),
  here("Simulation Results", "simple-models", "discrete", "binomial", "beta-prior", "beta-binomial-results-stan.rds")
)

poisson_gamma_bench_files <- c(
  here("Simulation Results", "simple-models", "discrete", "poisson", "gamma-prior", "poisson-gamma-results.rds"),
  here("Simulation Results", "simple-models", "discrete", "poisson", "gamma-prior", "poisson-gamma-results-greta.rds"),
  here("Simulation Results", "simple-models", "discrete", "poisson", "gamma-prior", "poisson-gamma-results-stan.rds")
)

hierarchical_beta_binomial_bench_files <- c(
  here("Simulation Results", "hierarchical-models", "beta-binomial", "hierarchical-beta-binomial-results.rds"),
  here("Simulation Results", "hierarchical-models", "beta-binomial", "hierarchical-beta-binomial-results-greta.rds"),
  here("Simulation Results", "hierarchical-models", "beta-binomial", "hierarchical-beta-binomial-results-stan.rds")
)

hierarchical_full_beta_binomial_bench_files <- c(
  here("Simulation Results", "hierarchical-models", "full-beta-binomial", "hierarchical-full-beta-binomial-results.rds"),
  here("Simulation Results", "hierarchical-models", "full-beta-binomial", "hierarchical-full-beta-binomial-results-greta.rds"),
  here("Simulation Results", "hierarchical-models", "full-beta-binomial", "hierarchical-full-beta-binomial-results-stan.rds")
)

hierarchical_logistic_regression_bench_files <- c(
  here("Simulation Results", "regression-models", "hierarchical-logistic-regression",  "hierarchical-logistic-regression-results.rds"),
  here("Simulation Results", "regression-models", "hierarchical-logistic-regression",  "hierarchical-logistic-regression-results-greta.rds"),
  here("Simulation Results", "regression-models", "hierarchical-logistic-regression",  "hierarchical-logistic-regression-results-stan.rds")
)

linear_regression_bench_files <- c(
  here("Simulation Results", "regression-models", "linear-regression",  "linear-regression-results.rds"),
  here("Simulation Results", "regression-models", "linear-regression",  "linear-regression-results-greta.rds"),
  here("Simulation Results", "regression-models", "linear-regression",  "linear-regression-results-stan.rds")
)

logistic_regression_bench_files <- c(
  here("Simulation Results", "regression-models", "logistic-regression",  "logistic-regression-results.rds"),
  here("Simulation Results", "regression-models", "logistic-regression",  "logistic-regression-results-greta.rds"),
  here("Simulation Results", "regression-models", "logistic-regression",  "logistic-regression-results-stan.rds")
)

poisson_regression_bench_files <- c(
  here("Simulation Results", "regression-models", "poisson-regression",  "poisson-regression-results.rds"),
  here("Simulation Results", "regression-models", "poisson-regression",  "poisson-regression-results-greta.rds"),
  here("Simulation Results", "regression-models", "poisson-regression",  "poisson-regression-results-stan.rds")
)

cox_exponential_bench_files <- c(
  here("Simulation Results", "survival-models", "cox-exponential-results.rds"),
  here("Simulation Results", "survival-models", "cox-exponential-results-greta.rds"),
  here("Simulation Results", "survival-models", "cox-exponential-results-stan.rds")
)

eight_schools_bench_files <- c(
  here("Simulation Results", "8-schools", "eight-schools-results.rds"),
  here("Simulation Results", "8-schools", "eight-schools-results-stan.rds")
)

ma_model_bench_files <- c(
  here("Simulation Results", "time-series", "ma-model", "ma-model-results.rds"),
  here("Simulation Results", "time-series", "ma-model", "ma-model-results-stan.rds")
)

ar_model_bench_files <- c(
  here("Simulation Results", "time-series", "ar-model", "ar-model-results-no-nimble.rds"),
  here("Simulation Results", "time-series", "ar-model", "ar-model-results-greta.rds"),
  here("Simulation Results", "time-series", "ar-model", "ar-model-stan-compile-results.rds")
)

files <- eight_schools_bench_files

model_name <- "8"

combine_bench <- function(files, model_name) {
  combined_results <- files %>% map_dfr(~ readRDS(.))
  combined_results
  
  # expression_string <- combined_results$expression[[7]]
  # expression_string
  get_method_name <- function(expression_string) {
    string <- as.character(expression_string)[1]
    string
    if (string == "run.jags") {
      method <- "JAGS"
    } else if (string == "bugs") {
      method <- "OpenBUGS"
    } else if (string == "nimbleMCMC") {
      method <- "Nimble"
    } else if (string == "stan") {
      method <- "Stan"
    } else if (string == "mcmc") {
      method <- "Greta"
    } else if (string == "stan_model") {
      method <- "Stan Compile"
    }
    method
  }
  
  method_names <- combined_results$expression %>% map_chr(get_method_name)
  
  method_mean <- combined_results$time %>% map_dbl(~ mean(.))
  method_sd <- combined_results$time %>% map_dbl(~ sd(.))
  
  results <- combined_results %>% 
    mutate(method = method_names, mean = method_mean, sd = method_sd, 
           model_name = model_name) %>% 
    select(method, mean, median, min, sd, n_itr, model_name)
  
  rows_to_keep <- results$method %>% unique() %>% 
    map_dbl(~ which(results$method == .)[1])
  
  results <- results[rows_to_keep,] %>% 
    arrange(method)
  
  
}

combine_bench_indiv <- function(files, model_name) {
  combined_results <- files %>% map_dfr(~ readRDS(.))
  combined_results
  
  # expression_string <- combined_results$expression[[7]]
  # expression_string
  get_method_name <- function(expression_string) {
    string <- as.character(expression_string)[1]
    string
    if (string == "run.jags") {
      method <- "JAGS"
    } else if (string == "bugs") {
      method <- "OpenBUGS"
    } else if (string == "nimbleMCMC") {
      method <- "Nimble"
    } else if (string == "stan") {
      method <- "Stan"
    } else if (string == "mcmc") {
      method <- "Greta"
    } else if (string == "stan_model") {
      method <- "Stan Compile"
    }
    method
  }
  
  method_names <- combined_results$expression %>% map_chr(get_method_name)
  
  times <- combined_results$time[[1]]
  
  time_results <- combined_results$time
  
  names(time_results) <- method_names
  
  get_iterations_for_method <- function(times, name) {
    tibble(
      method = name,
      time = times,
      model_name = model_name
    )
  }
  
  res <- time_results %>% imap_dfr(get_iterations_for_method)
  
  # 
  # method_mean <- combined_results$time %>% map_dbl(~ mean(.))
  # method_sd <- combined_results$time %>% map_dbl(~ sd(.))
  # 
  # results <- combined_results %>% 
  #   mutate(method = method_names, mean = method_mean, sd = method_sd, 
  #          model_name = model_name) %>% 
  #   select(method, mean, median, min, sd, n_itr, model_name)
  # 
  # rows_to_keep <- results$method %>% unique() %>% 
  #   map_dbl(~ which(results$method == .)[1])
  # 
  # results <- results[rows_to_keep,] %>% 
  #   arrange(method)
  
  res
  
  
}

# exp_gamma_results <- exp_gamma_bench_files %>% 
#   combine_bench("exponential_gamma")
# normal_gamma_tau_results <- normal_gamma_tau_bench_files %>%
#   combine_bench("normal_gamma_tau")
# normal_normal_results <- normal_normal_bench_files %>%
#   combine_bench("normal_normal")
# beta_bernoulli_results <- beta_bernoulli_bench_files %>%
#   combine_bench("beta_bernoulli")
# beta_binomial_results <- beta_binomial_bench_files %>%
#   combine_bench("beta_binomial")
# poisson_gamma_results <- poisson_gamma_bench_files %>%
#   combine_bench("poisson_gamma")
# hier_beta_binomial_results <- hierarchical_beta_binomial_bench_files %>%
#   combine_bench("hierarchical_beta_binomial")
# hier_full_bb_results <- hierarchical_full_beta_binomial_bench_files %>%
#   combine_bench("hierarchical_full_beta_binomial")
# hier_log_reg_results <- hierarchical_logistic_regression_bench_files %>%
#   combine_bench("hierarchical_logistic_regression")
# linear_reg_results <- linear_regression_bench_files %>% 
#   combine_bench("linear regression")
# logistic_reg_results <- logistic_regression_bench_files %>% 
#   combine_bench("logistic regression")
# poisson_reg_results <- poisson_regression_bench_files %>% 
#   combine_bench("poisson regression")

exp_gamma_results <- exp_gamma_bench_files %>% 
  combine_bench_indiv("exponential_gamma")
normal_gamma_tau_results <- normal_gamma_tau_bench_files %>%
  combine_bench_indiv("normal_gamma_tau")
normal_normal_results <- normal_normal_bench_files %>%
  combine_bench_indiv("normal_normal")
beta_bernoulli_results <- beta_bernoulli_bench_files %>%
  combine_bench_indiv("beta_bernoulli")
beta_binomial_results <- beta_binomial_bench_files %>%
  combine_bench_indiv("beta_binomial")
poisson_gamma_results <- poisson_gamma_bench_files %>%
  combine_bench_indiv("poisson_gamma")
hier_beta_binomial_results <- hierarchical_beta_binomial_bench_files %>%
  combine_bench_indiv("hierarchical_beta_binomial")
hier_full_bb_results <- hierarchical_full_beta_binomial_bench_files %>%
  combine_bench_indiv("hierarchical_full_beta_binomial")
hier_log_reg_results <- hierarchical_logistic_regression_bench_files %>%
  combine_bench_indiv("hierarchical_logistic_regression")
linear_reg_results <- linear_regression_bench_files %>% 
  combine_bench_indiv("linear regression")
logistic_reg_results <- logistic_regression_bench_files %>% 
  combine_bench_indiv("logistic regression")
poisson_reg_results <- poisson_regression_bench_files %>% 
  combine_bench_indiv("poisson regression")
cox_exp_results <- cox_exponential_bench_files %>% 
  combine_bench_indiv("cox exponential")
eight_schools_results <- eight_schools_bench_files %>% 
  combine_bench_indiv("eight schools")
ma_model_results <- ma_model_bench_files %>% 
  combine_bench_indiv("ma model")
ar_model_results <- ar_model_bench_files %>% 
  combine_bench_indiv("ar model")


```


```{r, eval = FALSE}
# bench_results <- bind_rows(
#   exp_gamma_results,
#   normal_gamma_tau_results,
#   normal_normal_results,
#   beta_bernoulli_results, 
#   beta_binomial_results,
#   poisson_gamma_results,
#   hier_beta_binomial_results,
#   hier_full_bb_results,
#   hier_log_reg_results,
#   linear_reg_results,
#   logistic_reg_results,
#   poisson_reg_results
# )
# 
# bench_results
# 
# saveRDS(bench_results, file = "bench_results.RDS")

bench_results_indiv <- bind_rows(
  exp_gamma_results,
  normal_gamma_tau_results,
  normal_normal_results,
  beta_bernoulli_results, 
  beta_binomial_results,
  poisson_gamma_results,
  hier_beta_binomial_results,
  hier_full_bb_results,
  hier_log_reg_results,
  linear_reg_results,
  logistic_reg_results,
  poisson_reg_results,
  cox_exp_results,
  eight_schools_results,
  ma_model_results,
  ar_model_results
)

bench_results_indiv

bench_results_indiv <- bench_results_indiv %>% 
  filter(!(method == "Stan Compile" & time < 5))

saveRDS(bench_results_indiv, file = "bench_results_indiv.RDS")
# saveRDS(bench_results_indiv, file = "bench_results_indiv2.RDS")
```

```{r}
# bench_results %>% 
#   ggplot(aes(mean, color = method)) + 
#   geom_boxplot() + 
#   coord_flip() + 
#   xlim(0,90)
# 
# bench_results %>% 
#   ggplot(aes(mean, fill = method)) + 
#   geom_histogram() + 
#   facet_wrap(vars(method))
#   # coord_flip() + 
#   # xlim(0,90)


```

```{r}
bench_results_indiv <- readRDS(here("bench_results_indiv.RDS"))

bench_results_indiv %>%
  ggplot(aes(x = method, y = time)) +
  geom_boxplot(aes(color = method), coef = 2, outlier.size = 0.75, size = 0.7) +
  # geom_boxplot(aes(color = method)) +
  # coord_flip() +
  ylim(0,90) +
  scale_x_discrete(limits = c("JAGS", "OpenBUGS", "Stan", "Nimble", "Greta", "Stan Compile")) + 
  theme(legend.position="none",
        plot.title = element_text(hjust = 0.5),
        text = element_text(size=20)) + 
  xlab("Implementation") + 
  ylab("Completion Time") + 
  ggtitle("Implementation Completion Time Boxplots")
  
  

bench_results_indiv %>%
  ggplot(aes(time, fill = method)) +
  geom_histogram(aes(y = stat(density)), bins = 20) + 
  # xlim(0,100) +
  facet_wrap(vars(method)) + 
  theme(legend.position="none",
        plot.title = element_text(hjust = 0.5),
        text = element_text(size=20)) + 
  ggtitle("Implementation Completion Time Histograms") + 
  xlab("Completion Time") + 
  ylab("Count Density")
  
  

bench_results_indiv %>%
  ggplot(aes(time, fill = method)) +
  geom_histogram(aes(y = stat(density)), bins = 20) + 
  xlim(0,100) +
  facet_wrap(vars(method)) + 
  theme(legend.position="none",
        plot.title = element_text(hjust = 0.5),
        text = element_text(size=20)) + 
  ggtitle("Implementation Completion Time Histograms") + 
  xlab("Completion Time") + 
  ylab("Count Density")

bench_results_indiv %>%
  filter(method %in% c("JAGS", "Nimble", "OpenBUGS", "Stan")) %>% 
  ggplot(aes(time, fill = method)) +
  geom_histogram(aes(y = stat(density)), bins = 20) + 
  # xlim(0,100) +
  facet_wrap(vars(method)) + 
  theme(legend.position="none",
        plot.title = element_text(hjust = 0.5),
        text = element_text(size=20)) + 
  ggtitle("Implementation Completion Time Histograms") + 
  xlab("Completion Time") + 
  ylab("Count Density")

```

<!-- ## Strip Charts -->

<!-- ```{r} -->
<!-- bench_results_indiv %>%  -->
<!--   mutate(model = model_name %>%  -->
<!--            str_replace_all("_", " ")) %>%  -->
<!--   ggplot(aes(method, time)) +  -->
<!--   geom_jitter(width = 0.1) +  -->
<!--   facet_wrap(vars(model)) +  -->
<!--   theme_update(panel.grid.minor = element_blank()) +  -->
<!--   scale_x_discrete(limits = c("JAGS", "OpenBUGS", "Stan",  "Nimble", "Greta", "Stan Compile")) +  -->
<!--   ylim(0,100) -->

<!-- bench_results_indiv %>%  -->
<!--   mutate(model = model_name %>%  -->
<!--            str_replace_all("_", " ")) %>%  -->
<!--   # filter(time < 100) %>%  -->
<!--   ggplot(aes(method, time, color = method)) +  -->
<!--   geom_jitter(width = 0.1) +  -->
<!--   facet_wrap(vars(model), scales = "free_y") +  -->
<!--   theme_update(panel.grid.minor = element_blank()) +  -->
<!--   scale_x_discrete(limits = c("JAGS", "OpenBUGS", "Stan",  "Nimble", "Greta", "Stan Compile")) -->


<!-- ``` -->

<!-- - First slide of strip charts -->
<!-- ```{r} -->
<!-- first_nine <- bench_results_indiv %>%  -->
<!--   mutate(model = model_name %>%  -->
<!--            str_replace_all("_", " ")) %>%  -->
<!--   group_by(model) %>%  -->
<!--   summarize(mean_time = mean(time)) %>%  -->
<!--   arrange(mean_time) %>%  -->
<!--   pull(model) %>%  -->
<!--   .[1:9] %>%  -->
<!--   sort() -->

<!-- # first_six <- bench_results_indiv %>%  -->
<!-- #   mutate(model = model_name %>%  -->
<!-- #            str_replace_all("_", " ")) %>%  -->
<!-- #   group_by(model) %>%  -->
<!-- #   summarize(mean_time = mean(time)) %>%  -->
<!-- #   arrange(mean_time) %>%  -->
<!-- #   pull(model) %>%  -->
<!-- #   .[1:6] %>%  -->
<!-- #   sort() -->

<!-- bench_results_indiv %>%  -->
<!--   mutate(model = model_name %>%  -->
<!--            str_replace_all("_", " ")) %>%  -->
<!--   filter(model %in% first_nine) %>%  -->
<!--   filter(time < 100) %>%  -->
<!--   ggplot(aes(method, time, color = method)) +  -->
<!--   geom_jitter(width = 0.2, size = 1) +  -->
<!--   # facet_wrap(vars(model), scales = "free_y") +  -->
<!--   facet_wrap(vars(model)) +  -->
<!--   theme_update(panel.grid.minor = element_blank()) +  -->
<!--   scale_x_discrete(limits = c("JAGS", "OpenBUGS", "Stan",  "Nimble", "Greta", "Stan Compile")) +  -->
<!--   labs(title = "Completion Time Strip Charts", subtitle = "Each individual simulation computation completion time shown, facetted by model") +  -->
<!--   theme(plot.title = element_text(hjust = 0.5, size = 20),  -->
<!--         plot.subtitle = element_text(hjust = 0.5),  -->
<!--         legend.position = "none",  -->
<!--         axis.text = element_text(size=10),  -->
<!--         axis.title = element_text(size = 13),  -->
<!--         axis.title.x = element_text(vjust = -1), -->
<!--         axis.title.y = element_text(vjust = 2))  +  -->
<!--   xlab("Implementation") +  -->
<!--   ylab("Completion Time") -->

<!-- # bench_results_indiv %>%  -->
<!-- #   mutate(model = model_name %>%  -->
<!-- #            str_replace_all("_", " ")) %>%  -->
<!-- #   filter(model %in% first_six) %>%  -->
<!-- #   filter(time < 100) %>%  -->
<!-- #   ggplot(aes(method, time, color = method)) +  -->
<!-- #   geom_jitter(width = 0.2) +  -->
<!-- #   # facet_wrap(vars(model), scales = "free_y") +  -->
<!-- #   facet_wrap(vars(model)) +  -->
<!-- #   theme_update(panel.grid.minor = element_blank()) +  -->
<!-- #   scale_x_discrete(limits = c("JAGS", "OpenBUGS", "Stan",  "Nimble", "Greta", "Stan Compile")) -->



<!-- ``` -->

<!-- - second slide -->

<!-- ```{r} -->
<!-- last_seven <- bench_results_indiv %>%  -->
<!--   mutate(model = model_name %>%  -->
<!--            str_replace_all("_", " ")) %>%  -->
<!--   group_by(model) %>%  -->
<!--   summarize(mean_time = mean(time)) %>%  -->
<!--   arrange(mean_time) %>%  -->
<!--   pull(model) %>%  -->
<!--   .[10:16] %>%  -->
<!--   sort() -->

<!-- bench_results_indiv %>%  -->
<!--   mutate(model = model_name %>%  -->
<!--            str_replace_all("_", " ")) %>%  -->
<!--   filter(model %in% last_seven) %>%  -->
<!--   filter(time < 100) %>%  -->
<!--   ggplot(aes(method, time, color = method)) +  -->
<!--   geom_jitter(width = 0.2, size = 1) +  -->
<!--   # facet_wrap(vars(model), scales = "free_y") +  -->
<!--   facet_wrap(vars(model)) +  -->
<!--   theme_update(panel.grid.minor = element_blank()) +  -->
<!--   scale_x_discrete(limits = c("JAGS", "OpenBUGS", "Stan",  "Nimble", "Greta", "Stan Compile")) +  -->
<!--   labs(title = "Completion Time Strip Charts", subtitle = "Each individual simulation computation completion time shown, facetted by model") +  -->
<!--   theme(plot.title = element_text(hjust = 0.5, size = 20),  -->
<!--         plot.subtitle = element_text(hjust = 0.5),  -->
<!--         legend.position = "none",  -->
<!--         axis.text = element_text(size=10),  -->
<!--         axis.title = element_text(size = 13),  -->
<!--         axis.title.x = element_text(vjust = -1), -->
<!--         axis.title.y = element_text(vjust = 2))  +  -->
<!--   xlab("Implementation") +  -->
<!--   ylab("Completion Time") -->
<!-- ``` -->


## Accuracy benchmarking

<!-- ```{r} -->
<!-- bugs_fit_condense <- readRDS(here("Simulation Results", "simple-models",  -->
<!--                                   "discrete", "binomial", "beta-prior",  -->
<!--                                   "bugs_fit_condense_beta_binomial.RDS")) -->
<!-- jags_fit_condense <- readRDS(here("Simulation Results", "simple-models",  -->
<!--                                   "discrete", "binomial", "beta-prior",  -->
<!--                                   "jags_fit_condense_beta_binomial.RDS")) -->
<!-- stan_fit_condense <- readRDS(here("Simulation Results", "simple-models",  -->
<!--                                   "discrete", "binomial", "beta-prior",  -->
<!--                                   "stan_fit_condense_beta_binomial.RDS")) -->
<!-- greta_fit_condense <- readRDS(here("Simulation Results", "simple-models",  -->
<!--                                   "discrete", "binomial", "beta-prior",  -->
<!--                                   "greta_fit_condense_beta_binomial.RDS")) -->
<!-- nimble_fit_condense <- readRDS(here("Simulation Results", "simple-models",  -->
<!--                                   "discrete", "binomial", "beta-prior",  -->
<!--                                   "nimble_fit_condense_beta_binomial.RDS")) -->
<!-- dists <- tibble( -->
<!--   x = c(bugs_fit_condense, jags_fit_condense, stan_fit_condense,  -->
<!--         greta_fit_condense, nimble_fit_condense), -->
<!--   method = c(rep("bugs", length(bugs_fit_condense)), -->
<!--              rep("jags", length(jags_fit_condense)), -->
<!--              rep("stan", length(stan_fit_condense)), -->
<!--              rep("greta", length(greta_fit_condense)), -->
<!--              rep("nimble", length(nimble_fit_condense)) -->
<!--              ) -->
<!-- ) -->

<!-- dists %>%  -->
<!--   ggplot(aes(x, color = method)) +  -->
<!--   geom_density(adjust = 2) +  -->
<!--   stat_function(fun = dbeta, args = list(3,9), color = "black") -->


<!-- tibble(x = bugs_fit_condense) %>%  -->
<!--   ggplot(aes(x)) +  -->
<!--     geom_density(adjust = 2) +  -->
<!--     stat_function(fun = dbeta, args = list(3,9), color = "red") -->

<!-- tibble(x = jags_fit_condense) %>%  -->
<!--   ggplot(aes(x)) +  -->
<!--     geom_density(adjust = 2) +  -->
<!--     stat_function(fun = dbeta, args = list(3,9), color = "red") -->

<!-- tibble(x = stan_fit_condense) %>%  -->
<!--   ggplot(aes(x)) +  -->
<!--     geom_density(adjust = 2) +  -->
<!--     stat_function(fun = dbeta, args = list(3,9), color = "red") -->


<!-- ``` -->

```{r}
exp_gamma_acc_files <- c(
  here("Simulation Results", "simple-models", "continuous", "exponential", "gamma-prior", "exponential-gamma-accuracy.rds"),
  here("Simulation Results", "simple-models", "continuous", "exponential", "gamma-prior", "exponential-gamma-accuracy-nimble.rds")
)

normal_gamma_tau_acc_files <- c(
  here("Simulation Results", "simple-models", "continuous", "normal", "gamma-prior-tau", "normal-gamma-tau-accuracy.rds"),
  here("Simulation Results", "simple-models", "continuous", "normal", "gamma-prior-tau", "normal-gamma-tau-accuracy-nimble.rds")
)

normal_normal_acc_files <- c(
  here("Simulation Results", "simple-models", "continuous", "normal", "normal-prior", "normal-normal-accuracy.rds"),
  here("Simulation Results", "simple-models", "continuous", "normal", "normal-prior", "normal-normal-accuracy-nimble.rds")
)

beta_bernoulli_acc_files <- c(
  here("Simulation Results", "simple-models", "discrete", "bernoulli", "beta-prior", "beta-bernoulli-accuracy.rds"),
  here("Simulation Results", "simple-models", "discrete", "bernoulli", "beta-prior", "beta-bernoulli-accuracy-nimble.rds")
)

beta_binomial_acc_files <- c(
  here("Simulation Results", "simple-models", "discrete", "binomial", "beta-prior", "beta-binomial-accuracy.rds"),
  here("Simulation Results", "simple-models", "discrete", "binomial", "beta-prior", "beta-binomial-accuracy-nimble.rds")
)

poisson_gamma_acc_files <- c(
  here("Simulation Results", "simple-models", "discrete", "poisson", "gamma-prior", "poisson-gamma-accuracy.rds"),
  here("Simulation Results", "simple-models", "discrete", "poisson", "gamma-prior", "poisson-gamma-accuracy-nimble.rds")
)

files <- poisson_gamma_acc_files
model_name <- "poisson_gamma"

combine_time_indiv <- function(files, model_name) {
  combined_results <- files %>% map_dfc(~ readRDS(.)) %>% 
    select(-iter, -iter1) %>% 
    mutate(model = model_name)
  
  # stan_mean <- combined_results$stan_dist %>% mean()
  stan_mean <- 1
  
  combined_results <- combined_results %>% 
    mutate(JAGS = jags_dist / stan_mean, 
           OpenBUGS = bugs_dist / stan_mean, 
           Stan = stan_dist / stan_mean, 
           Nimble = nimble_dist / stan_mean, 
           Greta = greta_dist / stan_mean
           )
  
  combined_results
}

exp_gamma_acc_df <- exp_gamma_acc_files %>% 
  combine_time_indiv("exponential_gamma")
normal_gamma_tau_acc_df <- normal_gamma_tau_acc_files %>% 
  combine_time_indiv("normal_gamma_tau")
normal_normal_acc_df <- normal_normal_acc_files %>%
  combine_time_indiv("normal_normal")
beta_bernoulli_acc_df <- beta_bernoulli_acc_files %>% 
  combine_time_indiv("beta_bernoulli")
beta_binomial_acc_df <- beta_binomial_acc_files %>% 
  combine_time_indiv("beta_binomial")
poisson_gamma_acc_df <- poisson_gamma_acc_files %>% 
  combine_time_indiv("poisson_gamma")

time_results <- bind_rows(
  exp_gamma_acc_df,
  normal_gamma_tau_acc_df,
  normal_normal_acc_df,
  beta_bernoulli_acc_df,
  beta_binomial_acc_df,
  poisson_gamma_acc_df
)
# 
# time_results %>% 
#   pivot_longer(
#     # cols = c(jags_dist, bugs_dist, stan_dist, greta_dist, nimble_dist), 
#     cols = c(JAGS, OpenBUGS, Stan, Nimble, Greta), 
#     names_to = "method",
#     values_to = "TVD"
#   ) %>% 
#   ggplot(aes(TVD)) + 
#     geom_histogram(aes(fill = method)) + 
#     facet_wrap(facets = "method") + 
#   theme(legend.position="none",
#         plot.title = element_text(hjust = 0.5),
#         text = element_text(size=20)) + 
#   ggtitle("Implementation TVD Accuracy Histograms") + 
#   xlab("Implementation") + 
#   ylab("TVD Ratio")
# 
# time_results %>% 
#   pivot_longer(
#     # cols = c(jags_dist, bugs_dist, stan_dist, greta_dist, nimble_dist), 
#     cols = c(JAGS, OpenBUGS, Stan, Nimble, Greta), 
#     names_to = "method",
#     values_to = "TVD_Ratio"
#   ) %>% 
#   ggplot(aes(x = method, y = TVD_Ratio)) + 
#     geom_boxplot(aes(color = method), size = 0.7) + 
#   ggtitle("Implementation TVD Accuracy Boxplots") + 
#   xlab("Implementation") + 
#   ylab("TVD Ratio") + 
#   scale_x_discrete(limits = c("OpenBUGS", "JAGS", "Nimble", "Stan", "Greta")) + 
#   theme(legend.position="none",
#         plot.title = element_text(hjust = 0.5),
#         text = element_text(size=20))

```

## Strip charts for time

- First slide of strip charts
```{r}
first_nine <- bench_results_indiv %>% 
  mutate(model = model_name %>% 
           str_replace_all("_", " ")) %>% 
  group_by(model) %>% 
  summarize(mean_time = mean(time)) %>% 
  arrange(mean_time) %>% 
  pull(model) %>% 
  .[1:9] %>% 
  sort()

# first_six <- bench_results_indiv %>% 
#   mutate(model = model_name %>% 
#            str_replace_all("_", " ")) %>% 
#   group_by(model) %>% 
#   summarize(mean_time = mean(time)) %>% 
#   arrange(mean_time) %>% 
#   pull(model) %>% 
#   .[1:6] %>% 
#   sort()

bench_results_indiv %>% 
  mutate(model = model_name %>% 
           str_replace_all("_", " ")) %>% 
  filter(model %in% first_nine) %>% 
  filter(time < 100) %>% 
  ggplot(aes(method, time, color = method)) + 
  geom_jitter(width = 0.2, size = 1) + 
  # facet_wrap(vars(model), scales = "free_y") + 
  facet_wrap(vars(model)) + 
  theme_update(panel.grid.minor = element_blank()) + 
  scale_x_discrete(limits = c("JAGS", "OpenBUGS", "Stan",  "Nimble", "Greta", "Stan Compile")) + 
  labs(title = "Completion Time Strip Charts", subtitle = "Each individual simulation computation completion time shown, facetted by model") + 
  theme(plot.title = element_text(hjust = 0.5, size = 20), 
        plot.subtitle = element_text(hjust = 0.5), 
        legend.position = "none", 
        axis.text = element_text(size=10), 
        axis.title = element_text(size = 13), 
        axis.title.x = element_text(vjust = -1),
        axis.title.y = element_text(vjust = 2))  + 
  xlab("Implementation") + 
  ylab("Completion Time (Seconds)")

# bench_results_indiv %>% 
#   mutate(model = model_name %>% 
#            str_replace_all("_", " ")) %>% 
#   filter(model %in% first_six) %>% 
#   filter(time < 100) %>% 
#   ggplot(aes(method, time, color = method)) + 
#   geom_jitter(width = 0.2) + 
#   # facet_wrap(vars(model), scales = "free_y") + 
#   facet_wrap(vars(model)) + 
#   theme_update(panel.grid.minor = element_blank()) + 
#   scale_x_discrete(limits = c("JAGS", "OpenBUGS", "Stan",  "Nimble", "Greta", "Stan Compile"))
  


```

- second slide

```{r}
last_seven <- bench_results_indiv %>% 
  mutate(model = model_name %>% 
           str_replace_all("_", " ")) %>% 
  group_by(model) %>% 
  summarize(mean_time = mean(time)) %>% 
  arrange(mean_time) %>% 
  pull(model) %>% 
  .[10:16] %>% 
  sort()

bench_results_indiv %>% 
  mutate(model = model_name %>% 
           str_replace_all("_", " ")) %>% 
  filter(model %in% last_seven) %>% 
  filter(time < 100) %>% 
  ggplot(aes(method, time, color = method)) + 
  geom_jitter(width = 0.2, size = 1) + 
  # facet_wrap(vars(model), scales = "free_y") + 
  facet_wrap(vars(model)) + 
  theme_update(panel.grid.minor = element_blank()) + 
  scale_x_discrete(limits = c("JAGS", "OpenBUGS", "Stan",  "Nimble", "Greta", "Stan Compile")) + 
  labs(title = "Completion Time Strip Charts", subtitle = "Each individual simulation computation completion time shown, facetted by model") + 
  theme(plot.title = element_text(hjust = 0.5, size = 20), 
        plot.subtitle = element_text(hjust = 0.5), 
        legend.position = "none", 
        axis.text = element_text(size=10), 
        axis.title = element_text(size = 13), 
        axis.title.x = element_text(vjust = -1),
        axis.title.y = element_text(vjust = 2))  + 
  xlab("Implementation") + 
  ylab("Completion Time (Seconds)")
```

- overall boxplot time

```{r}
bench_results_indiv %>% 
  mutate(model = model_name %>% 
           str_replace_all("_", " ")) %>% 
  filter(time < 100) %>% 
  ggplot(aes(method, time, color = method)) + 
  # geom_jitter(width = 0.2, size = 1) + 
  geom_boxplot() + 
  # facet_wrap(vars(model), scales = "free_y") + 
  # facet_wrap(vars(model)) + 
  theme_update(panel.grid.minor = element_blank()) + 
  scale_x_discrete(limits = c("JAGS", "OpenBUGS", "Stan",  "Nimble", "Greta", "Stan Compile")) + 
  labs(title = "Completion Time Overall Boxplots", subtitle = "Completion time aggregated across all models, for each implementation") + 
  theme(plot.title = element_text(hjust = 0.5, size = 20), 
        plot.subtitle = element_text(hjust = 0.5), 
        legend.position = "none", 
        axis.text = element_text(size=10), 
        axis.title = element_text(size = 13), 
        axis.title.x = element_text(vjust = -1),
        axis.title.y = element_text(vjust = 2))  + 
  xlab("Implementation") + 
  ylab("Completion Time (Seconds)")
```


- first chart accuracy
```{r}
time_results %>% 
  pivot_longer(
    # cols = c(jags_dist, bugs_dist, stan_dist, greta_dist, nimble_dist), 
    cols = c(JAGS, OpenBUGS, Stan, Nimble, Greta), 
    names_to = "method",
    values_to = "TVD"
  ) %>% 
  mutate(model = model %>% 
           str_replace_all("_", " ")) %>% 
  ggplot(aes(method, TVD, color = method)) + 
  geom_jitter(width = 0.1, size = 1) + 
  facet_wrap(vars(model)) +
  theme_update(panel.grid.minor = element_blank()) + 
  scale_x_discrete(limits = c("JAGS", "Stan", "Nimble", "OpenBUGS", "Greta")) + 
  xlab("Implementation") + 
   labs(title = "TVD Strip Charts", subtitle = "Each individual simulation TVD shown, facetted by model") + 
  theme(plot.title = element_text(hjust = 0.5, size = 20), 
        plot.subtitle = element_text(hjust = 0.5), 
        legend.position = "none", 
        axis.text = element_text(size=12), 
        axis.title = element_text(size = 15), 
        axis.title.x = element_text(vjust = -1),
        axis.title.y = element_text(vjust = 2))
```

- overall accuracy boxplot

```{r}
time_results %>% 
  pivot_longer(
    # cols = c(jags_dist, bugs_dist, stan_dist, greta_dist, nimble_dist), 
    cols = c(JAGS, OpenBUGS, Stan, Nimble, Greta), 
    names_to = "method",
    values_to = "TVD"
  ) %>% 
  mutate(model = model %>% 
           str_replace_all("_", " ")) %>% 
  ggplot(aes(method, TVD, color = method)) + 
  # geom_jitter(width = 0.1, size = 1) + 
  geom_boxplot() + 
  # facet_wrap(vars(model)) +
  theme_update(panel.grid.minor = element_blank()) + 
  scale_x_discrete(limits = c("JAGS", "Stan", "Nimble", "OpenBUGS", "Greta")) + 
  xlab("Implementation") + 
  labs(title = "TVD Overall Boxplots", subtitle = "TVD aggregated across all models, for each implementation") +
  theme(plot.title = element_text(hjust = 0.5, size = 20), 
        plot.subtitle = element_text(hjust = 0.5), 
        legend.position = "none", 
        axis.text = element_text(size=12), 
        axis.title = element_text(size = 15), 
        axis.title.x = element_text(vjust = -1),
        axis.title.y = element_text(vjust = 2))

# time_results %>%
#   pivot_longer(
#     # cols = c(jags_dist, bugs_dist, stan_dist, greta_dist, nimble_dist),
#     cols = c(JAGS, OpenBUGS, Stan, Nimble, Greta),
#     names_to = "method",
#     values_to = "TVD"
#   ) %>%
#   mutate(model = model %>%
#            str_replace_all("_", " ")) %>%
#   ggplot(aes(method, TVD, color = method)) +
#   # geom_jitter(width = 0.1, size = 1) +
#   geom_boxplot() +
#   # facet_wrap(vars(model)) +
#   theme_update(panel.grid.minor = element_blank()) +
#   scale_x_discrete(limits = c("JAGS", "Stan", "Nimble", "OpenBUGS", "Greta")) +
#   theme(
#     legend.position = "none"
#   ) +
#   xlab("Implementation") +
#   labs(title = "TVD Overall Boxplots", subtitle = "TVD aggregated across all models, for each implementation") +
#   theme(plot.title = element_text(hjust = 0.5),
#         plot.subtitle = element_text(hjust = 0.5))
# 

  
```

